version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "aitoai"
      POSTGRES_USER: "aitoai"
      POSTGRES_DB: "aitoai"
    ports:
      - "15432:5432"
    volumes:
      - ./.data:/var/lib/postgresql/data
