name: Pull Request CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: oven-sh/setup-bun@v1

    - name: Install Dependencies
      run: bun i

    - name: Check code style
      run: bun format:check

    - name: Generate prisma client
      run: bun prisma generate

    - name: Lint
      run: bun lint
