name: Pull Request CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Bun
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo "$HOME/.bun" >> $GITHUB_PATH

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.9.0'

    - name: Install Bun
      run: curl -fsSL https://bun.sh/install | bash

    - name: Install Dependencies
      run: bun i

    - name: Check code style
      run: bun format:check

    - name: Generate prisma client
      run: bun prisma generate

    - name: Lint
      run: bun lint
